name: example
description: Example project for Supa Manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supa_manager:
    path: ../
  shared_preferences: ^2.0.13
  flutter_riverpod: ^1.0.4
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  go_router: ^4.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  freezed: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/secrets.json
